# clone:
#   git:
#     image: woodpeckerci/plugin-git:latest
#     settings:
#       recursive: true
steps:
  publish:
    image: plugins/docker
    settings:
      registry: git.kapdee.uk
      repo: git.kapdee.uk/${CI_REPO}
      purge: false
    when:
      - branch: main
