clone:
   git:
     image: woodpeckerci/plugin-git
     settings:
       recursive: true

pipeline:
  publish:
    image: plugins/docker
    settings:
      registry: git.kapdee.uk
      repo: git.kapdee.uk/${CI_REPO}
      username: $CI_REPO_OWNER
      password:
        from_secret: registry_token
      purge: false
    when:
      branch: master
