steps:
  lfs:
    image: woodpeckerci/plugin-git
    commands:
      - git submodule foreach git lfs pull
      - git submodule foreach git lfs checkout
  publish:
    image: plugins/kaniko
    settings:
      registry: git.kapdee.uk
      repo: git.kapdee.uk/${CI_REPO}
      tags: latest
      dockerfile: dockerfile
      username: $CI_REPO_OWNER
      password:
        from_secret: packages_token
    when:
      - branch: main
