steps:
  publish:
    image: plugins/kaniko
    settings:
      registry: git.kapdee.uk
      repo: git.kapdee.uk/${CI_REPO}
      tags: latest
      dockerfile: dockerfile
    when:
      - branch: main
