steps:
  test:
    image: busybox
    commands:
      - sleep 1000
  publish:
    image: plugins/kaniko
    settings:
      registry: git.kapdee.uk
      repo: git.kapdee.uk/${CI_REPO}
      tags: latest
      dockerfile: dockerfile
      username: $CI_REPO_OWNER
      password:
        from_secret: packages_token
    when:
      - branch: main
