steps:
  test:
    image: busybox
    commands:
      - env
  publish:
    image: plugins/kaniko
    settings:
      registry: git.kapdee.uk
      repo: git.kapdee.uk/${CI_REPO}
      tags: latest
      dockerfile: dockerfile
      username: $CI_REPO_OWNER
      password: $PACKAGES_TOKEN
    when:
      - branch: main
